import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Phone, Clock, Home, Award } from 'lucide-react';
export default async function LabDashboard() { const session = await auth(); if (session?.user?.role !== 'LAB')
    redirect('/'); const lab = await prisma.medicalLab.findUnique({ where: { userId: session.user.id }, include: { services: { include: { service: true } } } }); if (!lab)
    redirect('/'); return (<div className='container py-8'>      <h1 className='text-3xl font-bold mb-2'>Lab Dashboard</h1>      <p className='text-muted-foreground mb-8'>{lab.name}</p>      <div className='grid md:grid-cols-2 gap-6'>        <Card><CardHeader><CardTitle>Profile Information</CardTitle></CardHeader><CardContent className='space-y-3'>          <p className='flex items-center gap-2'><MapPin className='h-4 w-4 text-muted-foreground'/>{lab.address}, {lab.city}</p>          {lab.phone && <p className='flex items-center gap-2'><Phone className='h-4 w-4 text-muted-foreground'/>{lab.phone}</p>}          {lab.openingHours && <p className='flex items-center gap-2'><Clock className='h-4 w-4 text-muted-foreground'/>{lab.openingHours}</p>}          <p className='flex items-center gap-2'><Home className='h-4 w-4 text-muted-foreground'/>Home Sample Collection: {lab.homeSampleCollection ? 'Yes' : 'No'}</p>          {lab.accreditation && <p className='flex items-center gap-2'><Award className='h-4 w-4 text-muted-foreground'/>{lab.accreditation}</p>}          {lab.licenseNumber && <p className='flex items-center gap-2'><Award className='h-4 w-4 text-muted-foreground'/>License: {lab.licenseNumber}</p>}          <Badge className={lab.status === 'VERIFIED' ? 'bg-green-600' : 'bg-amber-600'}>{lab.status}</Badge>        </CardContent></Card>        <Card><CardHeader><CardTitle>Available Tests</CardTitle></CardHeader><CardContent>{lab.services.length === 0 ? <p className='text-muted-foreground'>No tests listed</p> : <div className='flex flex-wrap gap-2'>{lab.services.map((s) => <Badge key={s.service.id} variant='secondary'>{s.service.name}</Badge>)}</div>}</CardContent></Card>      </div>      <div className='mt-6'><Card><CardHeader><CardTitle>Public Page</CardTitle></CardHeader><CardContent><a href={`/lab/${lab.slug}`} target='_blank' className='text-teal-700 hover:underline'>View your public listing</a></CardContent></Card></div>    </div>); }
