import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Phone, Clock, Truck, Shield } from 'lucide-react';
export default async function PharmacyDashboard() { const session = await auth(); if (session?.user?.role !== 'PHARMACY')
    redirect('/'); const pharmacy = await prisma.medicineShop.findUnique({ where: { userId: session.user.id }, include: { services: { include: { service: true } } } }); if (!pharmacy)
    redirect('/'); return (<div className='container py-8'>      <h1 className='text-3xl font-bold mb-2'>Pharmacy Dashboard</h1>      <p className='text-muted-foreground mb-8'>{pharmacy.name}</p>      <div className='grid md:grid-cols-2 gap-6'>        <Card><CardHeader><CardTitle>Profile Information</CardTitle></CardHeader><CardContent className='space-y-3'>          <p className='flex items-center gap-2'><MapPin className='h-4 w-4 text-muted-foreground'/>{pharmacy.address}, {pharmacy.city}</p>          {pharmacy.phone && <p className='flex items-center gap-2'><Phone className='h-4 w-4 text-muted-foreground'/>{pharmacy.phone}</p>}          {pharmacy.openingHours && <p className='flex items-center gap-2'><Clock className='h-4 w-4 text-muted-foreground'/>{pharmacy.openingHours}</p>}          <p className='flex items-center gap-2'><Truck className='h-4 w-4 text-muted-foreground'/>Home Delivery: {pharmacy.homeDelivery ? 'Yes' : 'No'}</p>          <p className='flex items-center gap-2'><Clock className='h-4 w-4 text-muted-foreground'/>24-Hour: {pharmacy.is24Hour ? 'Yes' : 'No'}</p>          {pharmacy.licenseNumber && <p className='flex items-center gap-2'><Shield className='h-4 w-4 text-muted-foreground'/>License: {pharmacy.licenseNumber}</p>}          <Badge className={pharmacy.status === 'VERIFIED' ? 'bg-green-600' : 'bg-amber-600'}>{pharmacy.status}</Badge>        </CardContent></Card>        <Card><CardHeader><CardTitle>Services</CardTitle></CardHeader><CardContent>{pharmacy.services.length === 0 ? <p className='text-muted-foreground'>No services listed</p> : <div className='flex flex-wrap gap-2'>{pharmacy.services.map((s) => <Badge key={s.service.id} variant='secondary'>{s.service.name}</Badge>)}</div>}</CardContent></Card>      </div>      <div className='mt-6'><Card><CardHeader><CardTitle>Public Page</CardTitle></CardHeader><CardContent><a href={`/pharmacy/${pharmacy.slug}`} target='_blank' className='text-teal-700 hover:underline'>View your public listing</a></CardContent></Card></div>    </div>); }
